### ISSUE TITLE
4.0.0 producing an exception

### ISSUE THREAD

**Issue by mhosman** [Havunen/SystemTextJsonPatch#37] opened 2024-10-22 00:46 UTC
Even with:

builder.Services.AddControllers().AddJsonOptions(options =>
{
        options.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
       ......
       
Is producing an exception since 4.0.0. The request is in camelCase. I also checked the patch before being applied, and the keys are in camelCase... so.. something is wrong

**Comment by Havunen** [comment] 2024-10-22 07:26
Can you provide more details of the payload, models, exception etc.

**Comment by tinchoel10** [comment] 2024-10-24 17:27
I'm having the same issue. It seems is happening with nullable integers? For example, hoy make a request with a nullable int, in camel case and is throwing an exception. This happens only with version 4

**Comment by Havunen** [comment] 2024-10-25 07:16
Can you show the request payload / model / naming convention?

**Comment by mhosman** [comment] 2024-11-07 15:16
Nevermind. The problem is when you send the path in lowercase. When you do that and you create a new Document for the entity (for example when sending a Dto document), then you need to convert the path to PascalCase.

**Comment by mhosman** [comment] 2024-11-07 22:22
The problem with this is that maybe you have configured camelCase for you api controllers and that's fine, but if you pass for example in your Path, something like "user" instead of "User", it will fail. Before this change, that worked in the past, and we are talking about the value, not the key.

**Comment by Havunen** [comment] 2024-11-08 07:12
The `path` must follow the API serialization configuration, previously it was ambiguously matching case insensitively anything that it found from the model, making PascalCase and CamelCase behave incorrectly when the model has "name" and "Name" properties defined. It would patch the property which it found using FirstOrDefault() which could be anything. 

Same way when POSTing a request to controller it matches only to the property which matches the naming convention. 

This is a breaking change and thus the major version was bumped. 

If the naming convention is correctly set in the request and the PATCH does not match to the property accordingly then that is a bug, but we need an example of the payload and model so we can fix it and create test case to avoid regression

**Comment by tinchoel10** [comment] 2024-11-09 20:04
I'm having the same issue too. The serialization is okay to be applied to keys, but not to values. That does not make any sense! JSON configuration for controllers can be configured in camelCase but class names will be always in PascalCase so will never work. This introduces a problem!

**Comment by mhosman** [comment] 2024-11-09 20:06
I agree. JSON settings should be apllied only in keys, not in the value of the key, or maybe I'm missing something.

**Comment by Havunen** [comment] 2024-11-10 11:32
Given following model:

```cs
class Foobar {
  public string Name { get; set; }
  public string name { get; set; }
  public int Age { get; set; }
}
```

If one has configured STJ naming contention camelCase and sends a regular POST request to asp.net endpoint 

```json
{ "Age": 10 }
```
That does not match anything the input model would have default value for all its fields, name(s)null, age 0,


Now in 4.0.0 the PATCH follows same convention

The following request:
```json
[{"op": "replace", "path": "Age", "value": 50}]
```

Does not match anything

Similarly prior to version 4
```json
[{"op": "replace", "path": "name", "value": "test"}]
```

Would have changed value of property Name instead of name because it did not follow STJs naming convention

**Comment by Havunen** [comment] 2024-11-10 11:35
> I agree. JSON settings should be apllied only in keys, not in the value of the key, or maybe I'm missing something.

Can you provide an example please. 

Its difficult to follow what is the value in this context, are you referring to path value or do you have nested object serialized into the value field of the operation

**Comment by mhosman** [comment] 2024-11-11 15:20
Okay I know what's happening. The problem is when you try to generate your own PatchDocument. Let's say you get a:

JsonPatchDocument<DtoUser> patchDocument

Sometimes, in complex scenarios, you need to receive that patchDocument and iterate through the operations. To create a new JsonPatchDocument<User> patchDocument (to convert from Dto to Entity and do some changes in the values).

If I save the changes will fail because because is not converting the received path to PascalCase. In other words, if you manually do this, will fail:

```
var document1 = new JsonPatchDocument<Customer>();
document1.Operations.Add(new Operation<Customer>("replace", "name", null, "name"));
document1.ApplyTo(customer);
await context.SaveChangesAsync();
```

If you do this:

```
var document1 = new JsonPatchDocument<Customer>();
document1.Operations.Add(new Operation<Customer>("replace", "Name", null, "name"));
document1.ApplyTo(customer);
await context.SaveChangesAsync();
```

Will work (no matter your JSON configuration).
This used to work fine before 4.0.0.

**Comment by Havunen** [comment] 2024-11-12 12:02
Does anybody know if its possible to inject default options from the WebApi settings?

**Comment by mhosman** [comment] 2024-11-12 15:53
Oh, gotcha! Thanks for that!

**Comment by Havunen** [comment] 2024-11-15 19:29
I updated the example in the readme to show how to pass the options. I'm closing this issue. If there is still an issue please create a new issue with repro

**Closed by Havunen** 2024-11-15 19:29 UTC
